bug fix5

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,15 +6,14 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      - name: "say hello"
-     	run: echo "hello world"
-  echo-goodby:
+        - name: "say hello"
+     	  run: echo "hello world"
+  echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-      - name: "fail step"
-        run: |
-	  echo "failed"
-	  exit 1
-      - name: "say goodbye"
-        if: always()
-        run: echo "goodbye"
+        - name: "fail step"
+          run: |
+	    echo "failed"
+	    exit 1
+        - name: "say goodbye"
+          run: echo "goodbye"
