bug fix6

diff --git a/.github/workflows/01-building-blocks.yaml b/.github/workflows/01-building-blocks.yaml
--- a/.github/workflows/01-building-blocks.yaml
+++ b/.github/workflows/01-building-blocks.yaml
@@ -6,14 +6,14 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-        - name: "say hello"
-     	  run: echo "hello world"
+      - name: "say hello"
+        shell: echo "hello world"
   echo-goodbye:
     runs-on: ubuntu-latest
     steps:
-        - name: "fail step"
-          run: |
-	    echo "failed"
-	    exit 1
-        - name: "say goodbye"
-          run: echo "goodbye"
+      - name: "fail step"
+        shell: |
+          echo "failed"
+	  exit 1
+      - name: "say goodbye"
+        shell: echo "goodbye"
